// AUTO-GENERATED by scripts/sync-properties.py — do not hand-edit.
// Source: ~/Desktop/LANDINGS (IMAGES/<ref>/, BROCHURES/<ref>.pdf), a
// folder outside this repo. Re-run the script after a new property's
// brochure+photos land in LANDINGS to pick up its ref.
//
// Keyed by property ref (matches CampaignMapEntry.ref in lib/config.ts,
// and the numeric ref embedded in historical campaign_name strings like
// "SP - 32785 - Finca Bugambilia" for leads whose campaign has since
// been retired from CAMPAIGN_MAP). price/agent are raw strings scraped
// from the brochure PDF text, not structured data — display as-is.
export interface PropertyInfo {
  price: string | null;
  location: string | null;
  agent: string | null;
  image: string | null;
}

export const PROPERTY_REGISTRY: Record<string, PropertyInfo> = {
  "31107": { price: "1.065.000 \u20ac", location: "Palmanova", agent: "Nathan Dilks", image: "/properties/31107.jpg" },
  "31653": { price: "22.500.000 \u20ac", location: "Bendinat", agent: "Angus Campbell", image: "/properties/31653.jpg" },
  "31740": { price: "1.375.000 \u20ac", location: "Puerto Portals", agent: "Rebuar Georg Wentz", image: "/properties/31740.jpg" },
  "31903": { price: "820.000 \u20ac", location: "Santa Catalina", agent: "Christopher C. Klatt", image: "/properties/31903.jpg" },
  "32065": { price: "7.950.000 \u20ac", location: "Santa Ponsa", agent: "Daniel Ballmann", image: "/properties/32065.jpg" },
  "32152": { price: "6.950.000 \u20ac", location: "Son Vida", agent: "Rebuar Georg Wentz", image: "/properties/32152.jpg" },
  "32206": { price: "5.900.000 \u20ac", location: "Bendinat", agent: "Angus Campbell", image: "/properties/32206.jpg" },
  "32242": { price: "7.390.000 \u20ac", location: "Santa Ponsa", agent: "Rebuar Georg Wentz", image: "/properties/32242.jpg" },
  "32254": { price: "4.750.000 \u20ac", location: "Costa D'En Blanes", agent: "Angus Campbell", image: "/properties/32254.jpg" },
  "32302": { price: "415.000 \u20ac", location: "Old Town", agent: "Anne Sophie Kayrak", image: "/properties/32302.jpg" },
  "32372": { price: "4.290.000 \u20ac", location: "Campos", agent: "Natalie Crossley", image: "/properties/32372.jpg" },
  "32432": { price: "699.950 \u20ac", location: "Bendinat", agent: "Natalie Crossley", image: "/properties/32432.jpg" },
  "32444": { price: "769.000 \u20ac", location: "San Agustin", agent: "Anne-Sophie Kayrak", image: "/properties/32444.jpg" },
  "32455": { price: "1.295.000 \u20ac", location: "Old Town", agent: "Sabine Kersten", image: "/properties/32455.jpg" },
  "32519": { price: "1.995.000 \u20ac", location: "Sol de Mallorca", agent: "Nathan Dilks", image: "/properties/32519.jpg" },
  "32590": { price: "3.350.000 \u20ac", location: "Santa Catalina", agent: "Michael Schwalbach", image: "/properties/32590.jpg" },
  "32606": { price: "1.200.000 \u20ac", location: "Calvia", agent: "Tim Schemann", image: "/properties/32606.jpg" },
  "32636": { price: "13.800.000 \u20ac", location: "Santa Ponsa", agent: "Daniel Ballmann", image: "/properties/32636.jpg" },
  "32666": { price: "4.750.000 \u20ac", location: "Felanitx", agent: "Christopher Calvin Klatt", image: "/properties/32666.jpg" },
  "32675": { price: "5.500.000 \u20ac", location: "Campos", agent: "Christopher Calvin Klatt", image: "/properties/32675.jpg" },
  "32692": { price: "2.250.000 \u20ac", location: "Palmanova", agent: "Angus Campbell", image: "/properties/32692.jpg" },
  "32716": { price: "1.300.000 \u20ac", location: "Cas Catala", agent: "Anne-Sophie Kayrak", image: "/properties/32716.jpg" },
  "32731": { price: "2.490.000 \u20ac", location: "Andratx", agent: "Cecilia Schwalbach", image: "/properties/32731.jpg" },
  "32777": { price: "315.000 \u20ac", location: "Calvia", agent: "Nathan Dilks", image: "/properties/32777.jpg" },
  "32780": { price: "3.200.000 \u20ac", location: "Costa d'en Blanes", agent: "Nathan Dilks", image: "/properties/32780.jpg" },
  "32785": { price: "4.350.000 \u20ac", location: "Santa Maria", agent: "Angus Campbell", image: "/properties/32785.jpg" },
  "32820": { price: "1.450.000 \u20ac", location: "Cala Vinyes", agent: "Nathan Dilks", image: "/properties/32820.jpg" },
  "32825": { price: "2.950.000 \u20ac", location: "Bendinat", agent: "Angus Campbell", image: "/properties/32825.jpg" },
  "6648": { price: "1.200.000 \u20ac", location: "Santa Catalina", agent: "Angus Campbell", image: "/properties/6648.jpg" },
};
